---
apiVersion: "cilium.io/v2alpha1"
kind: CiliumBGPPeerConfig
metadata:
  name: peer-config-generic
spec:
  families:
    - afi: ipv4
      safi: unicast
      advertisements:
        matchLabels:
          advertise: "pod-cidr"
  # timers:
  #   connectRetryTimeSeconds: 12
  #   holdTimeSeconds: 9
  #   keepAliveTimeSeconds: 3
