apiVersion: egressgateway.spidernet.io/v1beta1
kind: EgressGateway
metadata:
  name: poc-egw-gateway
spec:
  ippools:
    ipv4:
    - "192.168.20.200-192.168.20.202"
  nodeSelector:
    selector:
      matchLabels:
        egressgateway: "true"
