apiVersion: egressgateway.spidernet.io/v1beta1
kind: EgressPolicy
metadata:
 name: poc-egw-policy
 # namespace: 
spec:
 egressGatewayName: poc-egw-gateway
 appliedTo:
  podSelector:
   matchLabels:
    app: "poc-egw-pod"
