apiVersion: egressgateway.spidernet.io/v1beta1
kind: EgressPolicy
metadata:
 name: ep-cluster
# namespace: 
spec:
 egressGatewayName: default
 egressIP:                 # 
   ipv4: "172.18.0.110"                            
   ipv6: ""
   useNodeIP: false        # 
 appliedTo:
   podSelector:
    matchLabels:
     egw: "default"
