apiVersion: egressgateway.spidernet.io/v1beta1
kind: EgressPolicy
metadata:
 name: ep-cluster
# namespace: 
spec:
 egressGatewayName: default
 appliedTo:
  podSelector:
   matchLabels:
    egw: "default"
