apiVersion: apps/v1
kind: Deployment
metadata:
  name: wrk-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wrk
  template:
    metadata:
      labels:
        app: wrk
        app: poc-egw-pod
      annotations:
        k8s.v1.cni.cncf.io/networks: macvlan-ext-out-whereabouts
    spec:
      containers:
      - name: wrk-container
        image: your-docker-repo/wrk:latest # Replace with your image name
        command: ["/bin/sh"]
        args: ["-c", "wrk -t12 -c400 -d30s http://192.168.20.8/"]
        resources:
          limits:
            cpu: "200m"
            memory: "128Mi"
          requests:
            cpu: "100m"
            memory: "64Mi"
