apiVersion: apps/v1
kind: Deployment
metadata:
  name: egress-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: egress-gateway
  template:
    metadata:
      labels:
        app: egress-gateway
    spec:
      containers:
      - name: egress-gateway
        image: alpine
        command: ["/bin/sh", "-c", "while true; do sleep 3600; done"]
        securityContext:
          capabilities:
            add:
              - NET_ADMIN
#      nodeSelector:
#        kubernetes.io/hostname: <your-node-name>
