apiVersion: v1
kind: Pod
metadata:
  name: example-pod-multus-2-iface
  annotations:
   k8s.v1.cni.cncf.io/networks: secondary-network,macvlan-conf
spec:
  containers:
  - name: container
    image: nicolaka/netshoot
    command: ["tail", "-f", "/dev/null"]
    securityContext:
      capabilities:
        add:
        - NET_ADMIN
