apiVersion: v1
kind: Pod
metadata:
  name: example-pod-multus-hostnet-1-iface
  annotations:
   k8s.v1.cni.cncf.io/networks: macvlan-conf
spec:
  hostNetwork: true
  containers:
  - name: example-multus-host-1-iface
    image: nicolaka/netshoot
    command: ["tail", "-f", "/dev/null"]
    securityContext:
      capabilities:
        add:
        - NET_ADMIN
