apiVersion: v1
kind: Pod
metadata:
  name: example-pod-multus-mcvlan-vlan100
  annotations:
   k8s.v1.cni.cncf.io/networks: macvlan-vlan100-conf
spec:
  containers:
  - name: example-multus-mcvlan-vlan100
    image: nicolaka/netshoot
    command: ["tail", "-f", "/dev/null"]
    securityContext:
      capabilities:
        add:
        - NET_ADMIN
