apiVersion: egressgateway.spidernet.io/v1beta1
kind: EgressGateway
metadata:
  name: default
spec:
  ippools:
    ipv4:
    #- "172.22.0.100-172.22.0.110"
    - "172.18.0.100-172.18.0.110"
  nodeSelector:
    selector:
      matchLabels:
        egressgateway: "true"
